### ISSUE TITLE
Stopped working with Sonarr and Radarr

### ISSUE THREAD

**Issue by deandmx** [Shraymonks/unmonitorr#8]
All apps are the latest versions. This is the Radarr error I get:

`Failed to get movie information from radarr for tmdbId: XXXXXX XXXXXXXXXX
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at Api.getUrl (file:///usr/src/app/dist/utils.js:9:21)
    at unmonitorMovie (file:///usr/src/app/dist/radarr.js:18:52)
    at file:///usr/src/app/dist/index.js:43:24
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
    at done (/usr/src/app/node_modules/.pnpm/multer@1.4.5-lts.1/node_modules/multer/lib/make-middleware.js:45:7)
    at indicateDone (/usr/src/app/node_modules/.pnpm/multer@1.4.5-lts.1/node_modules/multer/lib/make-middleware.js:49:68)
    at Multipart.<anonymous> (/usr/src/app/node_modules/.pnpm/multer@1.4.5-lts.1/node_modules/multer/lib/make-middleware.js:166:7) {
  input: 'movie',
  code: 'ERR_INVALID_URL'
}`

This is the Sonarr error:

`Failed to get series lists from sonarr:
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at Api.getUrl (file:///usr/src/app/dist/utils.js:9:21)
    at unmonitorEpisode (file:///usr/src/app/dist/sonarr.js:23:48)
    at file:///usr/src/app/dist/index.js:41:24
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
    at done (/usr/src/app/node_modules/.pnpm/multer@1.4.5-lts.1/node_modules/multer/lib/make-middleware.js:45:7)
    at indicateDone (/usr/src/app/node_modules/.pnpm/multer@1.4.5-lts.1/node_modules/multer/lib/make-middleware.js:49:68)
    at Multipart.<anonymous> (/usr/src/app/node_modules/.pnpm/multer@1.4.5-lts.1/node_modules/multer/lib/make-middleware.js:166:7) {
  input: 'series',
  code: 'ERR_INVALID_URL'
}`

**Comment by Shraymonks** [comment]
Hey @deandmx,

Can you verify that `RADARR_HOST` and `SONARR_HOST` are set correctly? They must be valid URLs with the protocol included (`http://` or `https://`).

**Comment by deandmx** [comment]
I've checked that the address are correct. I'm also assuming that if they were incorrect I wouldn't be able to see the name of the movie or series being scrobbled from Plex? I manually redacted the movie name from the Radarr log.

**Comment by Shraymonks** [comment]
Do you mean the tmdbId and year? It gets that initial info from Plex.

The errors do indicate that there is something wrong with the urls.
When you start up unmonitorr it should log
```
Radarr: RADARR_HOST
Sonarr: SONARR_HOST
```

Are those the exact urls you use to access Radarr and Sonarr?

Everything should work from before, did the issue start happening after updating unmonitorr?

**Comment by deandmx** [comment]
They are, and if I copy and paste the URLs, they open the respective services.

I'm not sure when the problem started because I use watchtower to automatically update my containers.

**Comment by Shraymonks** [comment]
Is it possible to share one of these URLs?

I'm guessing there's maybe a subnet or port out of range or maybe a character that's causing the URL validation to fail.

**Comment by deandmx** [comment]
Radarr: "http://192.168.0.79:7878"
Sonarr: "http://192.168.0.79:8989"

**Comment by Shraymonks** [comment]
You don't have those quotes in the variables right? Otherwise that should be fine 🤔

**Comment by deandmx** [comment]
🙈 Mystery solved! So dumb, I hate computers lol. Thanks for troubleshooting with me.

**Comment by deandmx** [comment]
I might have spoken too soon. I have a new error in my log.

`unmonitoring for media.scrobble on port: 9797
Radarr: http://192.168.0.79:7878
Sonarr: http://192.168.0.79:8989
Failed to get series lists from sonarr:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6571:19)
    at successSteps (node:internal/deps/undici/undici:6545:27)
    at node:internal/deps/undici/undici:1211:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`
